server:
  build: .
  links:
   - db
  ports:
    - '5000:5000'
  environment:
    FLASK_APP: /taas/taas/app.py
    DATABASE_URI: db:5432

db:
  image: postgres:9.4
  ports:
    - '5432:5432'
  environment:
    POSTGRES_PASSWORD: 'mysecretpassword'
  volumes:
    - /tmp/usr/local/var/postgres:/var/lib/postgresql/data

celery:
  build: .
  links:
    - server
    - rabbitmq
  command: 'celery -A taas.tasks worker -l info -B'
  environment:
    API_CALLBACK_URL: 'http://server:5000'
    CELERY_BROKER_HOST: 'rabbitmq'
    CELERY_BROKER_USER: 'guest'

rabbitmq:
  image: rabbitmq:alpine